name: Create PR from Feature Branch

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches

      - name: Create local 'develop' branch
        run: git branch develop origin/develop

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "" # Defaults to the branch that triggered the workflow
          destination_branch: "develop"
          pr_title: "PR from ${{ github.ref_name }}"
          pr_body: "Automated PR from feature branch."
          github_token: ${{ secrets.GITHUB_TOKEN }}
